# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47cfe69e8a4d556ac83b618be5600767e9131e7e75ac85d87381274036217f622366cba17174f13b4e624aaaf5caf098b6e4a88dc808fcd89b6002b808b4851e
  ENV["LOCKUP_CODEWORD"]: 'jesus'
test:
  secret_key_base: 234abec3f64ff7b87347b15df73b6dca8a46395ae50548fdefa2b2be400345e5c063a5822668c16d24b88441a517e3d21f30e369b1464b24b33ab0034e7c2ce6
  ENV["LOCKUP_CODEWORD"]: 'jesus'
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
